apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  labels:
    app: hw4-firstapp
  name: hw4-firstapp
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hw4-firstapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hw4-firstapp
    spec:
      containers:
      - image: gcr.io/ds-561-first-project/serena-image:1.0.4
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
          limits:
            memory: "2048Mi"
        name: serena-image
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: gcloud-config
          mountPath: /root/.config/gcloud  
          subPath: application_default_credentials.json     
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: serenahw9-ksa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: gcloud-config
          secret:
            secretName: google-cloud-credentials 
